version: "3"

services:
  verdaccio:
    image: verdaccio/verdaccio:latest
    container_name: verdaccio
    ports:
      - "4873:4873"
    volumes:
      - "verdaccio:/verdaccio"
    restart: always

volumes:
  verdaccio:
    driver: local
